import fs from 'fs';

const phIcons = JSON.parse(fs.readFileSync('./node_modules/@iconify-json/ph/icons.json', 'utf8'));

const requiredIcons = [
  "envelope-duotone",
  "envelope-simple",
  "phone",
  "paper-plane-tilt",
  "envelope",
  "clock",
  "chat-centered-text",
  "globe-hemisphere-west",
  "map-pin-duotone",
  "target-duotone",
  "lightbulb-duotone",
  "star-duotone",
  "star-four-duotone",
  "lightning-duotone",
  "globe-duotone",
  "users-duotone",
  "buildings-duotone",
  "briefcase-duotone",
  "check-circle-duotone",
  "x-circle-duotone",
  "code-duotone",
  "puzzle-piece-duotone",
  "brain-duotone",
  "shield-check-duotone",
  "linkedin-logo-duotone",
  "twitter-logo-duotone",
  "github-logo-duotone",
  "currency-dollar-duotone",
  "arrow-left-duotone",
  "arrow-right",
  "file-search",
  "layout-duotone",
  "calendar-duotone",
  "clock-duotone",
  "link-duotone",
  "check-square-duotone",
  "credit-card-duotone",
  "paint-brush-duotone",
  "chart-line-duotone",
  "google-logo-duotone",
  "lock-key-duotone",
  "certificate-duotone",
  "lifebuoy-duotone",
  "handshake-duotone",
  "megaphone-duotone",
  "flow-chart-duotone",
  "wrench-duotone",
  "youtube-logo-duotone",
  "package-duotone",
  "chart-bar-duotone",
  "megaphone-simple-duotone",
  "palette-duotone",
  "tree-structure-duotone",
  "gear-six-duotone",
  "flow-arrow-duotone",
  "monitor-duotone",
  "ticket-duotone",
  "desktop-duotone",
  "presentation-chart-duotone",
  "trend-up-duotone",
  "first-aid-kit-duotone",
  "bank-duotone",
  "arrows-merge-duotone"
];

const missing = requiredIcons.filter(icon => !phIcons.icons[icon] && !phIcons.aliases?.[icon]);
console.log("Missing icons:", missing);
