export const captchas = [
  { q: "¿Cuánto es 2 + 2?", a: "4" },
  { q: "¿De qué color es el cielo despejado de día?", a: "azul" },
  { q: "¿Cuántas patas tiene un perro normal?", a: "4" },
  { q: "¿Qué animal maúlla?", a: "gato" },
  { q: "¿Cuál es la capital de Francia?", a: "paris" },
  { q: "¿Cuánto es 5 + 5?", a: "10" },
  { q: "¿Qué líquido bebemos para sobrevivir?", a: "agua" },
  { q: "¿Cuántos días tiene una semana?", a: "7" },
  { q: "¿De qué color es la sangre humana?", a: "rojo" },
  { q: "¿Qué número sigue después del 3?", a: "4" },
  { q: "¿Cuánto es 10 - 5?", a: "5" },
  { q: "¿En qué planeta vivimos?", a: "tierra" },
  { q: "¿Qué animal da leche y dice 'muuu'?", a: "vaca" },
  { q: "¿Cuántos dedos tiene una mano normal?", a: "5" },
  { q: "¿Qué herramienta se usa para clavar clavos?", a: "martillo" },
  { q: "¿De qué color es una naranja madura?", a: "naranja" },
  { q: "¿Cuánto es 3 x 3?", a: "9" },
  { q: "¿Qué calienta nuestro planeta durante el día?", a: "sol" },
  { q: "¿Cuál es la primera letra del abecedario?", a: "a" },
  { q: "¿Qué animal ladra?", a: "perro" },
  { q: "¿Cuántos meses tiene un año?", a: "12" },
  { q: "¿De qué color son las hojas de un árbol en primavera?", a: "verde" },
  { q: "¿Cuánto es 8 / 2?", a: "4" },
  { q: "¿Qué usamos para ver en la oscuridad si no hay electricidad?", a: "linterna" },
  { q: "¿Cómo se llama el centro de un huevo?", a: "yema" },
  { q: "¿Qué fruta amarilla es famosa por gustarle a los monos?", a: "platano" },
  { q: "¿Cuánto es 1 + 1?", a: "2" },
  { q: "¿Cuál es el opuesto de 'arriba'?", a: "abajo" },
  { q: "¿Qué vehículo tiene dos ruedas y pedales?", a: "bicicleta" },
  { q: "¿De qué color es la nieve?", a: "blanco" },
  { q: "¿Cuánto es 20 - 10?", a: "10" },
  { q: "¿Cuál es el opuesto de 'frío'?", a: "caliente" },
  { q: "¿Qué usamos en los pies antes de ponernos los zapatos?", a: "medias" },
  { q: "¿De qué animal obtenemos la lana?", a: "oveja" },
  { q: "¿Cuánto es 4 + 4?", a: "8" },
  { q: "¿En qué mes celebramos la Navidad?", a: "diciembre" },
  { q: "¿Qué mueble usamos para dormir?", a: "cama" },
  { q: "¿De qué color es un tomate maduro?", a: "rojo" },
  { q: "¿Cuánto es 6 - 2?", a: "4" },
  { q: "¿Qué usamos en la cabeza para protegernos del sol?", a: "sombrero" },
  { q: "¿Qué animal tiene una trompa larga?", a: "elefante" },
  { q: "¿Cuál es el opuesto de 'noche'?", a: "dia" },
  { q: "¿Qué objeto usamos para cortar papel?", a: "tijeras" },
  { q: "¿De qué color es el carbón?", a: "negro" },
  { q: "¿Cuánto es 7 + 3?", a: "10" },
  { q: "¿Qué idioma hablamos en la mayoría de Latinoamérica?", a: "español" },
  { q: "¿Qué animal salta y tiene una bolsa para sus crías?", a: "canguro" },
  { q: "¿Cuál es el opuesto de 'grande'?", a: "pequeño" },
  { q: "¿Qué usamos en los ojos para ver mejor?", a: "lentes" },
  { q: "¿Cuánto es 5 x 2?", a: "10" }
];
